### PR TITLE
Add ImmutableMappable support

### LINKED ISSUE #27: Problem when working with ImmutableMappable
When you try to map the JSON to an object that conforms to ImmutableMappable, you get the following error.

> assertion failed: BaseMappable should not be implemented directly. Please implement Mappable, StaticMappable or ImmutableMappable:

Is there a way to get around this?

Kind regards,
Frederik

### PR DESCRIPTION
**Pull request by devxoul**
It fixes #27 and https://github.com/Hearst-DD/ObjectMapper/pull/666

### CODE REVIEW

**Comment by arctouch-marcelogobetti** [comment]
Hi @devxoul , I just installed Moya-ObjectMapper pointing to this commit in your repository in my Podfile and the assertion failed still happens. Even with your definitions specifically for `ImmutableMappable`, the existent methods for `BaseMappable` are still the ones that end up being used. Attaching screenshot from Xcode's debugger.
mapobject basemappable
Thank you!

**Comment by devxoul** [comment]
@arctouch-marcelogobetti, could you please provide me the code you used?

**Comment by arctouch-marcelogobetti** [comment]
Unfortunately I can't, but here's an easy way to reproduce the issue: take the Samples project from `Moya-ObjectMapper` repository and edit the `Repository` struct by implementing `ImmutableMappable` instead of `Mappable`. You'll need to replace the `init` method by the one matching this new protocol, then run and you'll get at the failed assertion. Thank you once again :D

**Comment by devxoul** [comment]
Hmmmm, that's odd 🤔 I've tested with similar environment. I replaced existing struct `Repository` with the code below and it worked.

```swift
struct Repository: ImmutableMappable {
  let id: Int
  let name: String
  let owner: Owner

  init(map: Map) throws {
    self.id = try map.value("id")
    self.name = try map.value("name")
    self.owner = try map.value("owner")
  }
}
```

**Comment by arctouch-marcelogobetti** [comment]
@devxoul you are right. This fails on my own code but doesn't fail in the environment I said. When I tested that environment, I was accidentally not using your fix. I'll try to check here why is this behavior difference occurring, since I just installed `Moya-ObjectMapper` on both in exactly the same way (by specifying your repo URL and your branch)

**Comment by arctouch-marcelogobetti** [comment]
@devxoul finally found it: my method is returning an `Observable<T>` instead of a `T`, and you have defined specific `ImmutableMappable` methods only at `Response+ObjectMapper`, but we'll also need that at `Observable+ObjectMapper` (part of `Moya-ObjectMapper/RxSwift`). Could you please add this fix to your branch? Thank you very much!

**Comment by devxoul** [comment]
@arctouch-marcelogobetti, Of course! I have just updated. Could you please try with it again? If it works, let's wait for @ivanbruel :)

**Comment by ivanbruel** [comment]
Sorry for the late response, was busy with WebSummit, will look into this in a few hours and get back to you :)

**Pull request merged**
